#!/bin/sh

set -eu

atcoder-tools gen --skip-existing-problems $1 \
&& ls -d $1/*/ | xargs -I {} cp -r templates/.vscode/ {}/.vscode 

if [ $# -eq 2 ]; then
  echo  "cd $1/$2" | pbcopy 
else
  echo  "cd $1" | pbcopy 
fi
